2016-07-06 15:44:18,647 [Thread-2:139698802128640] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/xiaozhiqi/.pyenv/versions/2.7.11/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/xiaozhiqi/workplace/blog_project/blog_project/urls.py", line 18, in <module>
    from blog import views
  File "/home/xiaozhiqi/workplace/blog_project/blog/views.py", line 3
SyntaxError: Non-ASCII character '\xe9' in file /home/xiaozhiqi/workplace/blog_project/blog/views.py on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
2016-07-08 10:36:27,753 [Thread-5:139911931643648] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-07-08 11:18:34,893 [Thread-2:140631428749056] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1456, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 703, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (date_publish) specified for Article. Check fields/fieldsets/exclude attributes of class ArticleAdmin.
2016-07-08 11:18:37,039 [Thread-3:140631428749056] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1456, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 703, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (date_publish) specified for Article. Check fields/fieldsets/exclude attributes of class ArticleAdmin.
2016-07-08 11:19:11,106 [Thread-2:140110232065792] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1456, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 703, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (date_publish) specified for Article. Check fields/fieldsets/exclude attributes of class ArticleAdmin.
2016-07-08 11:19:20,365 [Thread-7:140110232065792] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1456, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 703, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (date_publish) specified for Article. Check fields/fieldsets/exclude attributes of class ArticleAdmin.
2016-07-08 11:19:34,544 [Thread-2:140590477760256] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1456, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 703, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (date_publish) specified for Article. Check fields/fieldsets/exclude attributes of class ArticleAdmin.
2016-07-08 11:19:35,950 [Thread-3:140590477760256] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1456, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 703, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (date_publish) specified for Article. Check fields/fieldsets/exclude attributes of class ArticleAdmin.
2016-07-08 11:19:36,738 [Thread-4:140590477760256] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1456, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 703, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (date_publish) specified for Article. Check fields/fieldsets/exclude attributes of class ArticleAdmin.
2016-07-08 11:19:37,460 [Thread-5:140590477760256] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1456, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 703, in get_form
    % (e, self.__class__.__name__))
FieldError: Unknown field(s) (date_publish) specified for Article. Check fields/fieldsets/exclude attributes of class ArticleAdmin.
2016-07-08 11:30:31,517 [Thread-15:139920386221824] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1467, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1078, in save_model
    obj.save()
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1048, "Column 'user_id' cannot be null")
2016-07-08 11:32:27,113 [Thread-21:139920169498368] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/article/add/
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1516, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1467, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1078, in save_model
    obj.save()
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/base.py", line 822, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/base.py", line 861, in _do_insert
    using=using, raw=raw)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1048, "Column 'user_id' cannot be null")
2016-07-10 15:15:15,105 [Thread-26:140711761491712] [django.request:170] [base:get_response] [WARNING]- Not Found: /uploads/2016/07/little-cat.jpg
2016-07-10 15:16:05,359 [Thread-2:140650414528256] [django.request:170] [base:get_response] [WARNING]- Not Found: /uploads/2016/07/little-cat.jpg
2016-07-10 15:16:06,139 [Thread-3:140650414528256] [django.request:170] [base:get_response] [WARNING]- Not Found: /uploads/2016/07/little-cat.jpg
2016-07-10 15:16:06,394 [Thread-4:140650414528256] [django.request:170] [base:get_response] [WARNING]- Not Found: /uploads/2016/07/little-cat.jpg
2016-07-10 15:16:06,589 [Thread-5:140650414528256] [django.request:170] [base:get_response] [WARNING]- Not Found: /uploads/2016/07/little-cat.jpg
2016-07-10 15:16:06,772 [Thread-6:140650414528256] [django.request:170] [base:get_response] [WARNING]- Not Found: /uploads/2016/07/little-cat.jpg
2016-07-10 18:32:07,637 [Thread-2:140118922954496] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/workplace/blog_project/blog/views.py", line 29, in index
    return render(request,'index.html',locals())
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'extends'base.html''
2016-07-10 18:32:08,458 [Thread-3:140118914299648] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/workplace/blog_project/blog/views.py", line 29, in index
    return render(request,'index.html',locals())
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'extends'base.html''
2016-07-10 18:32:08,907 [Thread-4:140118905906944] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/workplace/blog_project/blog/views.py", line 29, in index
    return render(request,'index.html',locals())
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'extends'base.html''
2016-07-10 18:32:09,347 [Thread-5:140118897514240] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/workplace/blog_project/blog/views.py", line 29, in index
    return render(request,'index.html',locals())
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'extends'base.html''
2016-07-10 18:32:09,737 [Thread-6:140118889121536] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xiaozhiqi/workplace/blog_project/blog/views.py", line 29, in index
    return render(request,'index.html',locals())
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 339, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/xiaozhiqi/blog_env/lib/python2.7/site-packages/django/template/base.py", line 395, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'extends'base.html''
2016-07-10 18:52:03,674 [Thread-357:140118897514240] [django.request:170] [base:get_response] [WARNING]- Not Found: /admn
2016-07-10 19:01:54,469 [Thread-12:140321874765568] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.html
2016-07-10 19:01:56,217 [Thread-13:140321874765568] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.html
2016-07-10 19:01:57,750 [Thread-14:140321960691456] [django.request:170] [base:get_response] [WARNING]- Not Found: /index.html
2016-07-10 19:14:02,517 [Thread-25:140365277415168] [django.request:170] [base:get_response] [WARNING]- Not Found: /329275108@qq.com
